{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mpfleu6ldbd5xc5qvca4752bqm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.5.0.aar",
          "url": "idnow-platform-4.5.0.aar",
          "size": 16975541,
          "sha512": "a5f7aa214ec0753df6bf3c293bc981fad7d385afb6c11d20144d30f61d396bd6c0371513fb15e48f7701ab95635bc83d1c5c63a9988313b505f9eb9ae9a0a4da",
          "sha256": "a81f9c11262d96f41b3c77701b24b6e5d2303566b8a825c452af3a7e42584dd7",
          "sha1": "f6de7c955917ad692ced20c2c5462a006961fa15",
          "md5": "3265dbf229dd5be518e1d93eda8ad6f3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.5.0.aar",
          "url": "idnow-platform-4.5.0.aar",
          "size": 16975541,
          "sha512": "a5f7aa214ec0753df6bf3c293bc981fad7d385afb6c11d20144d30f61d396bd6c0371513fb15e48f7701ab95635bc83d1c5c63a9988313b505f9eb9ae9a0a4da",
          "sha256": "a81f9c11262d96f41b3c77701b24b6e5d2303566b8a825c452af3a7e42584dd7",
          "sha1": "f6de7c955917ad692ced20c2c5462a006961fa15",
          "md5": "3265dbf229dd5be518e1d93eda8ad6f3"
        }
      ]
    }
  ]
}
