{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "oyohdbflczcxhig6cpntgyk7lm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.5.0.aar",
          "url": "idnow-platform-4.5.0.aar",
          "size": 16975200,
          "sha512": "e9ff331ec95d129f0a98a835d5d67f38d7739fa6780b8e89bf86b101c15d42b5cdeafb1f1959667a86e216c53639bd6d0630b9b6f385f1c0e70d51707dc02859",
          "sha256": "84111c7e6cb154ae0d1d83dc92350c18dbf6c713e54c6b8a47ba2472c6d77db2",
          "sha1": "6c78a35f03b03fabf0b4f428cae0ded01aba1b98",
          "md5": "3b90c2f9c667dfea6a0d1451923d3399"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.5.0.aar",
          "url": "idnow-platform-4.5.0.aar",
          "size": 16975200,
          "sha512": "e9ff331ec95d129f0a98a835d5d67f38d7739fa6780b8e89bf86b101c15d42b5cdeafb1f1959667a86e216c53639bd6d0630b9b6f385f1c0e70d51707dc02859",
          "sha256": "84111c7e6cb154ae0d1d83dc92350c18dbf6c713e54c6b8a47ba2472c6d77db2",
          "sha1": "6c78a35f03b03fabf0b4f428cae0ded01aba1b98",
          "md5": "3b90c2f9c667dfea6a0d1451923d3399"
        }
      ]
    }
  ]
}
